# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungwoo Shim
title: AI Researcher at ETRI
email: jshim0978@gmail.com
website: jshim0978.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jshim0978
github_username: jshim0978
instagram_username: j_w_shim
linkedin_username: "Jungwoo Shim"

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jungwoo Shim, and I am an AI Researcher at ETRI (Electronics and Telecommunications Research Institute). I recently completed my M.S. in Artificial Intelligence from Korea University Graduate School of Artificial Intelligence, where my research focused on mitigating large language model hallucinations through multi-stage prompt refinement. I have a solid foundation in computer science from Chungnam National University, and I am skilled in various programming languages and technologies including Python, Java, React.js, and AI/ML frameworks. I am passionate about large language models, AI research, and their applications in real-world scenarios.

content:
  - title: Publications & Patents # New section for publications
    layout: list
    content:
      - layout: top-middle
        title: Patent: 치료적 프롬프트 정제를 통해 언어 모델의 환각 오류를 감소시키는 방법, 장치, 및 프로그램
        sub_title: KR Application No. 10-2024-0102366 · 출원일: 2024년 8월 1일
        caption: 2024
        description: |
          Method, device, and program for reducing hallucination errors in language models through therapeutic prompt refinement.

      - layout: top-middle
        title: CPR: Mitigating Large Language Model Hallucinations with Curative Prompt Refinement
        sub_title: IEEE International Conference on Systems, Man, and Cybernetics (IEEE SMC 2024)
        caption: 2024
        description: |
          Research paper presenting a novel approach to mitigating hallucinations in large language models through curative prompt refinement techniques.

      - layout: top-middle
        title: Multi-stage Prompt Refinement for Mitigating Hallucinations in Large Language Models
        sub_title: Pattern Recognition (Under Review)
        caption: 2024
        description: |
          Comprehensive study on multi-stage prompt refinement techniques for reducing hallucinations in large language models.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Research Projects
        description: |
          **LLM Development for Chemical Control Systems**  
          *Agency for Defense Development (ADD), Korea*  
          **Role:** Researcher  
          **Period:** Oct 2023 - Jan 2024  
          - Developed a large language model (LLM) for chemical control systems.
          - Contributed significantly to the AI capabilities in the defense sector.

          **LLM Assistant for Elementary School Teachers**  
          *I-Scream Education, Korea*  
          **Role:** Researcher  
          **Period:** May 2023 - Nov 2023  
          - Fine-tuned the Polyglot-kr model to assist elementary school teachers.
          - Adjusted the model's tone to be appropriate for young learners.

      - layout: top-middle
        title: Engineering Projects
        description: |
          **KakaoPay API Payments System**  
          *Mobile Entropy, Korea*  
          **Role:** Backend Engineer  
          **Period:** May 2022 - Jan 2023  
          - Set up and integrated the KakaoPay API for gas bill payments, streamlining the payment process for users.
          - Ensured secure and efficient processing of payments through the KakaoPay platform.

          **System Monitoring with Prometheus and Grafana**  
          *Mobile Entropy, Korea*  
          **Role:** Backend Engineer  
          **Period:** May 2022 - Jan 2023  
          - Developed and deployed a comprehensive system monitoring solution using Prometheus and Grafana.
          - Monitored the company’s services hosted on Naver Cloud, improving operational reliability and performance.

          **Giro Payment Service using Open API**  
          *Mobile Entropy, Korea*  
          **Role:** Frontend Engineer  
          **Period:** Jan 2022 - Apr 2022  
          - Developed frontend interfaces and integrated Open API for secure payments.
          - Contributed to the enhancement of fintech solutions.

          **IoT Smart Safety System**  
          *Mobile Entropy, Korea*  
          **Role:** Frontend Developer & IoT Logic Developer  
          **Period:** Jun 2021 - Dec 2021  
          - Developed IoT manipulation logic and frontend interfaces for workplace safety.
          - Improved safety standards with smart IoT solutions.

      - layout: top-middle
        title: Academic Projects
        description: |
          **Improving the Argus-SAF Tool**  
          *Chungnam National University, Korea*  
          **Role:** Researcher  
          **Period:** Feb 2020 - Nov 2020  
          - Enhanced an APK analysis tool for mitigating malware risks in Android applications.

          **Predicting Sexual Orientation Using Survey Data**  
          *Chungnam National University, Korea*  
          **Role:** Student Researcher  
          **Period:** Sep 2020 - Dec 2020  
          - Applied machine learning techniques to analyze social science survey data.

          **Predicting the Probability of Winning in League of Legends**  
          *Chungnam National University, Korea*  
          **Role:** Student Researcher  
          **Period:** Mar 2020 - Jun 2020  
          - Developed a model to predict match outcomes based on draft picks using data analysis and machine learning.

    - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Electronics and Telecommunications Research Institute (ETRI)
        link: 
        sub_title: AI Researcher
        caption: 2025/07 - Present
        quote: >
          Currently working as an AI researcher at ETRI, focusing on cutting-edge artificial intelligence research and development.
        description: | # this will include new lines to allow paragraphs
            - Conducting research in artificial intelligence and machine learning
            - Contributing to innovative AI solutions and technologies

      - layout: left
        title: Mobile Entropy
        link: 
        sub_title: Web Developer
        caption: 2021/02 - 2023/01
        quote: >
          Developed and maintained web services for gas company clients, leading front-end and supporting back-end integration.
        description: | # this will include new lines to allow paragraphs
            - Led frontend development for various web applications
            - Supported backend integration and system architecture
            - Worked on payment systems, IoT safety monitoring, and cloud infrastructure

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea University Graduate School of Artificial Intelligence
        caption: 2023/03 - 2025/02
        sub_title: M.S. in Artificial Intelligence
        quote: >
          Master's Thesis: "Multi-stage Prompt Refinement for Mitigating Hallucinations in Large Language Models"
        description: | # this will include new lines to allow paragraphs
          Specialized in large language models and prompt engineering techniques, with research focused on reducing hallucinations in AI systems.

      - layout: left
        title: Chungnam National University
        caption: 2015/03 - 2021/02
        sub_title: B.S. in Computer Science
        quote: >
          Completed undergraduate studies in computer science.
        description: | # this will include new lines to allow paragraphs
          Built a strong foundation in programming, algorithms, and software development.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my academic and professional interests, I have a number of hobbies and passions:
      - Rock climbing
      - Gaming
      - Exploring new technologies
      - [Learning new skills](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Here is an interesting image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
